[package]
name = "file-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
clap = { version = "4.5.31", features = ["derive"] }
rpassword = "7.3.1"
rand_core = { version = "*", features = ["getrandom"] }
hex = "0.4.3"

[[bin]]
name = "file-encryption"
path = "main.rs"
